import {
  FEEDS_ENDPOINT,
  FEEDS_TRENDING_ENDPOINT,
  SUBSCRIBE_ENDPOINT,
  UNSUBSCRIBE_ENDPOINT,
} from '@/network';

export {
  FEEDS_ENDPOINT,
  FEEDS_TRENDING_ENDPOINT,
  SUBSCRIBE_ENDPOINT,
  UNSUBSCRIBE_ENDPOINT,
};
